### ISSUE TITLE
QUESTION: Namespace Packages

### ISSUE THREAD

**Issue by achapkowski** [pypa/sample-namespace-packages#18]
With namespace packages, you do not put the `__init__.py` in the root of the namespace, does setup.py create one?

**Comment by webknjaz** [comment]
@achapkowski no. The implicit PEP 420 namespace packages don't need it at all. Only old-style namespace packages (like the ones in Python 2) used to require this file to be present: https://packaging.python.org/guides/packaging-namespace-packages/#native-namespace-packages.

**Comment by achapkowski** [comment]
So if the parent package doesn't exist, is there a way to create the root namespace ```__init__.py```?

I can get my extension package to install but the root, which let's call `freesoda` has no init file, so I cannot do:

```import freesode.auth```

If `freesoda` doesn't exist, how can I create the `__init__.py`?  Is this another package type?

**Comment by webknjaz** [comment]
> I can get my extension package to install but the root, which let's call `freesoda` has no init file, so I cannot do:
> 
> `import freesode.auth`
> 
> If `freesoda` doesn't exist, how can I create the `__init__.py`? Is this another package type?

You just need to have a proper directory structure. `freesoda` does not need to exist. For your `freesoda.auth` you need to make sure to have a directory `freesoda/auth/` and that's it. No `__init__.py` needed. This way if you create `freesoda.auth` and `freesoda.utils`, they will be installed side-by-side under the `freesoda/` folder in `auth/` and `utils/` folders respectively while there will be no `__init__.py` in `freesoda/` itself — it's just unnecessary, `import freesoda.auth, freesoda.utils` will still work.

**Comment by achapkowski** [comment]
ok, the issue was with my system i think.  Thank you for your help @webknjaz

**Comment by webknjaz** [comment]
JFYI if you attempt to install a few packages in the same namespace that use different namespacing setup method (with and without `__init__.py`), this will indeed cause problems.

**Comment by achapkowski** [comment]
so the parent package can't have an ```__init__.py```?

**Comment by webknjaz** [comment]
It can but only if you use old-fashioned namespacing methods. Also, I don't remember if you can have the top-level `freesoda` at all. But yes, if some of your namespace packages include it and others don't, this will likely cause problems.
