### ISSUE TITLE
CI wrongly considers `noxfile.py` is designed for all sessions to pass

### ISSUE THREAD

**Issue by abravalheri** [pypa/sample-namespace-packages#26]
The sessions in `noxfile.py` were not originally designed to be evaluated in terms of "passing".
Instead, by analysing the README we can see that the original intent of the `noxfile.py` was to generate an informative table that will include situations where combining methods will pass and other where it will not pass... Making all the sessions in nox pass kind of defeat this purpose, isn't it?

Probably a clearer approach (however more costly in terms of computing resources and time), would be to run all the sessions in `noxfile.py`, build the new `table.md` using the reporting instructions described in the `README.md` and then fail if there is any uncommitted alteration in that file specifically.

**Comment by chrysle** [comment]
Sounds good! I'll take a look at that.

**Comment by abravalheri** [comment]
This might be useful in the context of running the whole nox matrix to generate the complete compatibility report:

https://github.com/actions/setup-python/releases/tag/v4.4.0

**Comment by chrysle** [comment]
> fail if there is any uncommitted alteration in that file specifically

One concern I have is that there might be different results across different Python versions (that's what this repository is intended to determine, right), for which the user can't possibly determine the compatibility, thus running the whole workflow with different Python versions on a pull request will most probably result in a CI failure?

**Comment by abravalheri** [comment]
Hi @chrysle, I believe the best is to run all the Python versions from a since CI job.
Probably https://github.com/actions/setup-python/releases/tag/v4.4.0 can be used for that.

Otherwise, it would be necessary to find out a way of integrating the report from different jobs, before converting them to a table. Individually running `nox` for a single Python version is not really useful to determine if the tests fail or not.

This happens because the `noxfile.py` was designed to run all the sessions (with the different Python versions) at once and only at the end of all sessions, generate a report file (which can then be processed by the script that creates the table).

I don't think this fits in the idea of mapping each Python version to a different CI job (running in a different container/VM).

**Comment by chrysle** [comment]
> I believe the best is to run all the Python versions from a since CI job

I agree with that. But if I've understood correctly, the different table reports for the Python versions will be combined into one compatibility matrix. And if running the `nox` sessions results with, for example, 3.10, in a different table than with 3.8,
which the user employed to update the table, won't the CI process on a PR fail?

**Comment by abravalheri** [comment]
Umm, I don't know if I understand the problem.

Let's suppose that in the CI, we use `setup-python` to install in the same CI job worker, Python versions: 3.8, 3.10 and 3.12. To ensure `noxfile.py` works well, then we have to set the environment variable the environment variable `USE_PYTHON_VERSIONS="3.8 3.10 3.12"`="3.8 3.10 3.12"` before running `nox`. This way it should not matter (🤞) which we use to install `nox`, for each different section `nox` should take care of spawning the correct virtual environments and combining then consistently when reporting.

Now if contributors want to update the `table.md` file, in their personal computer they will also need to install the same Python versions used in the CI and set the environment variable `USE_PYTHON_VERSIONS="3.8 3.10 3.12"` before using the procedure described in the `README.md`.

This is how I suppose it would work, but the best would be actually check that against the github CI. Maybe other unforeseen errors will appear...

If that is too complicated, we can also drop all togheter this idea of checking if `table.md` is updated accordingly... Just pick the combinations of Python versions and `nox` sessions that we know should work and only run those...

**Comment by chrysle** [comment]
Thanks for your patience, I suppose I had a little short-circuit here. I'll look into implementing that soon.

**Comment by abravalheri** [comment]
@chrysle this is a quick test I did to see if a single job can run multiple nox sessions:

https://github.com/abravalheri/experiment-setup-python-multiple-versions/actions/runs/7891544198/job/21536102814

I used a [`.python-version`](https://github.com/abravalheri/experiment-setup-python-multiple-versions/blob/f17a44e5b14eca92fac740f60bcc3e2973310538/.python-version#L1) to maintain a single source of truth for both [Github Actions](https://github.com/abravalheri/experiment-setup-python-multiple-versions/blob/f17a44e5b14eca92fac740f60bcc3e2973310538/.github/workflows/ci.yml#L18-L22) and [`nox`](https://github.com/abravalheri/experiment-setup-python-multiple-versions/blob/f17a44e5b14eca92fac740f60bcc3e2973310538/noxfile.py#L7).

**Comment by abravalheri** [comment]
Yeap, there should be no problem with that.
