### ISSUE TITLE
using native (no pkg __init__) in py2

### ISSUE THREAD

**Issue by asmodehn** [pypa/sample-namespace-packages#4]
It seems to me that the main point PEP 420 implicit namespace package, is that every directory is considered a  package, even if there is no `__init__.py` in there.

I noticed the result table does not reflect this, but it was for me a major hassle while developing a custom importer (relying on this for python3), and porting it to python2.

So I developed a custom importer and loader (see https://github.com/asmodehn/filefinder2) for python2.7, precisely because I needed **implicit** namespace packages.

I was wondering if that would relate to the features tested here, enough to be meaningful ?
If so, how should I go about integrating filefinder2 to the list of tests here ?

**Comment by jonparrott** [comment]
@asmodehn I would recommend reaching out to distutils-sig. :)
